### ISSUE TITLE
Cosas para arreglar para la parte 3

### ISSUE THREAD

**Issue by nhsz** [eebalcarcel/project-one-fakemdn#68]
- [x] En el `fakeForEach`, eliminar el valor de retorno de la documentación
- [x] Usar una [fuente monoespaciada](https://fonts.google.com/?category=Monospace) para las secciones de código
- [x] falta `fakeSome`
- [x] El array tiene que ser el 1er parámetro en todas las funciones
- [x] El `fakeIncludes` tiene que devolver -1 si el elemento no está
- [x] Faltan las páginas de algunas funciones
- [x] Agregar al `index.html` los links a las páginas que faltan
- [x] Modificar el `fakeEvery` (sin usar el `fakeForEach`) para que corte y retorna cuando encuentra el primer valor que no cumpla (esto fue culpa de Nico)
- Otra forma de hacer el `fakeIndexOxRecursive`

```js
function fakeIndexOfRecursive(arr, searchedElem, index = 0) {
  if (arr[0] === searchedElem) {
    return index;
  }

  if (arr.length === 0) {
    return -1;
  }

  return fakeIndexOfRecursive(arr.slice(1), searchedElem, index + 1);
}
```
- [x] usar nombres más declarativos para los nombres de los arrays (`mappedArray` por ej, para el `fakeMap`)
- [x] usar [`fakeReduce` en el `fakeSum`](https://github.com/caroribada/project-one-fakemdn/blob/629f916b27c6b32e273b9aac4a3bb7ad9cf4be4e/app.js#L58)

**Comment by marirumo** [comment]
@eebalcarcel @luchosr actualicé la function fakeEvery
